datasets:
  early:
    participant_tsv: /nfs/trident3/lightsheet/prado/mouse_app_lecanemab_batch2/bids/participants.tsv
    spimquant_dir: /nfs/trident3/lightsheet/prado/mouse_app_lecanemab_batch2/derivatives/spimquant-v0.6.0rc2_84a605e_ozx
  late:
    participant_tsv: /nfs/trident3/lightsheet/prado/mouse_app_lecanemab_batch3/bids/participants.tsv
    spimquant_dir: /nfs/trident3/lightsheet/prado/mouse_app_lecanemab_batch3/derivatives/spimquant-v0.6.0rc2_84a605e_ozx


